version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Ensure this password is correct and matches with your Django settings
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Make sure this is the same as above
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
